[package]
name = "shovel"
version = "0.2.0"
edition = "2021"
authors = ["Ong Yong Xin"]
description = "A package manager for Windows, based off of Scoop."

[dependencies]
git2 = "0.18.2"
home = "0.5.9"
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_with = "3.6.1"
thiserror = "1.0.57"
url = { version = "2.5.0", features = ["serde"] }

# CLI dependencies
anyhow = { version = "1.0.80", optional = true }
clap = { version = "4.5.1", features = ["derive"], optional = true }
tabled = { version = "0.15.0", features = ["ansi"], optional = true }
chrono = { version = "0.4.35", optional = true }
phf = { version = "0.11.2", features = ["macros"] }
colored = "2.1.0"
terminal_size = "0.3.0"

[features]
bin = ["dep:anyhow", "dep:clap", "dep:tabled", "dep:chrono"]

[[bin]]
name = "shovel"
required-features = ["bin"]

[profile.release]
debug = true
lto = true
codegen-units = 1
