[package]
name = "shovel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
clap = { version = "4.5.1", features = ["derive"] }
git2 = "0.18.2"
glob = "0.3.1"
home = "0.5.9"
regex = "1.10.3"
regress = "0.9.0"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_tuple = "0.5.0"
serde_with = "3.6.1"
thiserror = "1.0.57"
url = { version = "2.5.0", features = ["serde"] }

