[package]
name = "shovel"
version = "0.2.0"
edition = "2021"
authors = ["Ong Yong Xin"]
description = "A package manager for Windows, based off of Scoop."

[dependencies]
chrono = "0.4.35" 
git2 = "0.18.2"
home = "0.5.9"
regex = "1.10.3"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
serde_with = "3.6.1"
thiserror = "1.0.57"
url = { version = "2.5.0", features = ["serde"] }

# CLI dependencies
color-eyre = { version = "0.6", optional = true }
eyre = { version = "0.6", default-features = false, features = ["auto-install", "track-caller"], optional = true }
clap = { version = "4.5.1", features = ["derive"], optional = true }
tabled = { version = "0.15.0", features = ["ansi"], optional = true }
phf = { version = "0.11.2", features = ["macros"], optional = true }
owo-colors = { version = "3.5.0", optional = true }
terminal_size = { version = "0.3.0", optional = true}
serde_path_to_error = "0.1.16"

[features]
bin = ["dep:color-eyre", "dep:eyre", "dep:clap", "dep:tabled", "dep:phf", "dep:owo-colors", "dep:terminal_size"]

[[bin]]
name = "shovel"
required-features = ["bin"]

[profile.release]
debug = true
lto = true
codegen-units = 1
